### ISSUE TITLE
Getting Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by cenap** [likeastore/elaster#8]
When I run elaster I get:

I:\Projeler\nodejs\elaster\node_modules\elasticsearch\src\lib\log.js:65
Log.prototype.listenerCount = function (event) {
                                       ^

RangeError: Maximum call stack size exceeded
    at Log.listenerCount (I:\Projeler\nodejs\elaster\node_modules\elasticsearch\src\lib\log.js:65:40)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (I:\Projeler\nodejs\elaster\node_modules\elasticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (I:\Projeler\nodejs\elaster\node_modules\elasticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (I:\Projeler\nodejs\elaster\node_modules\elasticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (I:\Projeler\nodejs\elaster\node_modules\elasticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)

**Comment by maneeshmp** [comment]
same here

s-bson: Failed to load c++ bson extension, using pure JS version
events.js:410
EventEmitter.listenerCount = function(emitter, type) {
                                     ^

RangeError: Maximum call stack size exceeded
    at Function.EventEmitter.listenerCount (events.js:410:38)
    at Log.listenerCount (/home/maneesh/go/elaster/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:412:20)
    at Log.listenerCount (/home/maneesh/go/elaster/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:412:20)
    at Log.listenerCount (/home/maneesh/go/elaster/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:412:20)
    at Log.listenerCount (/home/maneesh/go/elaster/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:412:20)
    at Log.listenerCount (/home/maneesh/go/elaster/node_modules/elasticsearch/src/lib/log.js:68:25)

**Comment by Ema0** [comment]
Any news about this? I'm having the same error too:

```
js-bson: Failed to load c++ bson extension, using pure JS version
~/elaster/node_modules/elasticsearch/src/lib/log.js:65
Log.prototype.listenerCount = function(event){
                                      ^
RangeError: Maximum call stack size exceeded
at Log.listenerCount (~\elaster\node_modules\elasticsearch\src\lib\log.js:65:40)
at Function.EventEmitter.listenerCount (events.js:412:20)
at Log.listenerCount (~\elaster\node_modules\elasticsearch\src\lib\log.js:68:25)
at Function.EventEmitter.listenerCount (events.js:412:20)
at Log.listenerCount (~\elaster\node_modules\elasticsearch\src\lib\log.js:68:25)
at Function.EventEmitter.listenerCount (events.js:412:20)
at Log.listenerCount (~\elaster\node_modules\elasticsearch\src\lib\log.js:68:25)
at Function.EventEmitter.listenerCount (events.js:412:20)
at Log.listenerCount (~\elaster\node_modules\elasticsearch\src\lib\log.js:68:25)
at Function.EventEmitter.listenerCount (events.js:412:20)
```

**Comment by nicomse** [comment]
Im reopening this thread, im still having this error, RangeError: Maximum call stack size exceeded
    at Log.listenerCount (/home/ec2-user/projects/elaster/node_modules/elasticsearch/src/lib/log.js:65:40)
    at Function.EventEmitter.listenerCount (events.js:447:20)
    at Log.listenerCount (/home/ec2-user/projects/elaster/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:447:20)
    at Log.listenerCount (/home/ec2-user/projects/elaster/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:447:20)
    at Log.listenerCount (/home/ec2-user/projects/elaster/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:447:20)
    at Log.listenerCount (/home/ec2-user/projects/elaster/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:447:20)

**Comment by nicomse** [comment]
Solved updating elasticsearch npm module
